name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build DotNetCoreProject/DotNetCoreProject.csproj
    - name: Test with dotnet
      run: dotnet test DotNetCoreProject/DotNetCoreProject.csproj
    - name: Container Structure Tests
      uses: brpaz/structure-tests-action@v1.1.2
      with:
        # The Docker image to test
        image: navb/hellodocker
        # Path to the config file
        configFile: cstdemo/ContainerStructureTestSamples/FileExistenceTest.yml
      
